# Generated by Django 4.0.2 on 2022-02-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insertDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('Digestates', models.TextField(max_length=200)),
                ('Feedstock', models.TextField(max_length=200)),
                ('pH', models.FloatField()),
                ('DM', models.FloatField()),
                ('OM', models.FloatField()),
                ('TOC', models.FloatField()),
                ('TOC_TN', models.FloatField()),
                ('TN', models.FloatField()),
                ('NH4_N', models.FloatField()),
                ('NH4_TN', models.FloatField()),
            ],
        ),
    ]